//
//  CitiesPresenter.swift
//  Cities
//
//  Created by Vadym Riznychok on 9/28/17.
//  Copyright (c) 2017 Vadym Riznychok. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CitiesPresentationLogic {
    func presentSomething(response: Cities.Something.Response)
}

class CitiesPresenter: CitiesPresentationLogic {
    weak var viewController: CitiesDisplayLogic?
  
    // MARK: Do something
  
    func presentSomething(response: Cities.Something.Response) {
        let viewModel = Cities.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
