//
//  CitiesModels.swift
//  Cities
//
//  Created by Vadym Riznychok on 9/28/17.
//  Copyright (c) 2017 Vadym Riznychok. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Cities {
    // MARK: Use cases
  
    enum Something {
        struct Request {
        }
        
        struct Response {
        }
    
        struct ViewModel {
        }
    }
}
