//
//  CitiesInteractor.swift
//  Cities
//
//  Created by Vadym Riznychok on 9/28/17.
//  Copyright (c) 2017 Vadym Riznychok. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CitiesBusinessLogic {
    func doSomething(request: Cities.Something.Request)
}

protocol CitiesDataStore {
    //var name: String { get set }
}

class CitiesInteractor: CitiesBusinessLogic, CitiesDataStore {
    var presenter: CitiesPresentationLogic?
    var worker: CitiesWorker?
    //var name: String = ""
  
    // MARK: Do something
  
    func doSomething(request: Cities.Something.Request) {
        worker = CitiesWorker()
        worker?.doSomeWork()
    
        let response = Cities.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
