//
//  CitiesModels.swift
//  Cities
//
//  Created by Dima Tsurkan on 9/28/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Cities {
    // MARK: Use cases
  
    enum FetchCities {
        struct Request {
        }
        
        struct Response {
        }
    
        struct ViewModel {
            class DisplayedCity: NSObject {
                var name: String
                var countryCode: String
                var details: String
                var weatherDetails: Cities.FetchWeather.ViewModel.CityWeather?
                
                init(name: String, countryCode: String, details: String) {
                    self.name = name
                    self.countryCode = countryCode
                    self.details = details
                }
            }
            
            var displayedCities: [DisplayedCity]
        }
    }
    
    enum FetchWeather {
        struct Request {
            let city: Cities.FetchCities.ViewModel.DisplayedCity
            
            init(city: Cities.FetchCities.ViewModel.DisplayedCity) {
                self.city = city
            }
        }
        
        struct Response {
        }
        
        struct ViewModel {
            
            class CityWeather: NSObject {
                var temperature: Float
                var details: String
                
                init(temperature: Float, details: String) {
                    self.temperature = temperature
                    self.details = details
                }
            }
            
        }
    }
}
